package de.jeff_media.AngelChestPlus;

public class Config {

    public static final String CHECK_FOR_UPDATES = "check-for-updates";
    public static final String CHECK_FOR_UPDATES_INTERVAL = "check-interval";
    public static final String CONFIG_VERSION = "config-version";
    public static final String CONFIG_PLUGIN_VERSION = "plugin-version";
    public static final String DEBUG = "debug";
    public static final String VERBOSE = "verbose";
    public static final String CONSOLE_MESSAGE_ON_OPEN = "console-message-on-open";
    public static final String ANGELCHEST_DURATION = "angelchest-duration";
    public static final String MAX_ALLOWED_ANGELCHESTS = "max-allowed-angelchests";
    public static final String ALLOW_ANGELCHEST_IN_PVP = "allow-angelchest-in-pvp";
    public static final String MAX_RADIUS = "max-radius";
    public static final String SHOW_LOCATION = "show-location";
    public static final String SHOW_LINKS_ON_SEPARATE_LINE = "show-links-on-separate-line";
    public static final String MATERIAL = "material";
    public static final String HEAD_USES_PLAYER_NAME = "head-uses-player-name";
    public static final String CUSTOM_HEAD_BASE64 = "custom-head-base64";
    public static final String VOID_DETECTION = "void-detection";
    public static final String DONT_SPAWN_ON = "dont-spawn-on";
    public static final String ONLY_SPAWN_IN = "only-spawn-in";
    public static final String REMOVE_CURSE_OF_VANISHING = "remove-curse-of-vanishing";
    public static final String REMOVE_CURSE_OF_BINDING = "remove-curse-of-binding";
    public static final String TOTEM_OF_UNDYING_WORKS_EVERYWHERE = "totem-of-undying-works-everywhere";
    public static final String AUTO_RESPAWN = "auto-respawn";
    public static final String AUTO_RESPAWN_DELAY = "auto-respawn-delay";
    public static final String PRICE = "price";
    public static final String REFUND_EXPIRED_CHESTS = "refund-expired-chests";
    public static final String PRICE_TELEPORT = "price-teleport";
    public static final String PRICE_FETCH = "price-fetch";
    public static final String CONFIRM = "confirm";
    public static final String DISABLED_MATERIALS = "disabled-materials";
    public static final String DISABLED_WORLDS = "disabled-worlds";
    public static final String DISABLED_WORLDGUARD_REGIONS = "disabled-worldguard-regions";
    public static final String DISABLE_WORLDGUARD_INTEGRATION = "disable-worldguard-integration";
    public static final String ONLY_SPAWN_CHESTS_IF_PLAYER_MAY_BUILD = "only-spawn-chests-if-player-may-build";
    public static final String USE_SLIMEFUN = "use-slimefun";
    public static final String CHECK_GENERIC_SOULBOUND = "check-generic-soulbound";
    public static final String DETECT_PLAYER_HEAD_DROPS = "detect-player-head-drops";
    public static final String EVENT_PRIORITY = "event-priority";
    public static final String HOLOGRAM_OFFSET = "hologram-offset";
    public static final String HOLOGRAM_OFFSET_PER_LINE = "hologram-offset-per-line";
    public static final String LINK_UNLOCK = "link-unlock";
    public static final String LINK_UNLOCK_FOR = "link-unlock-for";
    public static final String LINK_FETCH = "link-fetch";
    public static final String LINK_TELEPORT = "link-teleport";
    public static final String HOLOGRAM_TEXT = "hologram-text";
    public static final String ANGELCHEST_INVENTORY_NAME = "angelchest-inventory-name";
    public static final String ANGELCHEST_LIST = "angelchest-list";
}
